# EnviiLock by Kaushallrai (adapted)
# Source: https://github.com/Kaushallrai/hyprlock
# Run: cd /home/digerati/Projects/hyprlock-netlogin-themes && hyprlock -c hyprlock.conf

general {
    hide_cursor = true
}

background {
    path = ./assets/too_close.jpg
    reload_time = 0
    crossfade_time = 0.5
}

image {
    path = ./assets/avatar.png
    size = 130
    rounding = 0
    border_size = 0
    border_color = rgba(255, 255, 255, 0.1)
    rotate = 0
    reload_time = -1
    position = 0, -50
    halign = center
    valign = center
}

input-field {
    size = 300, 45
    outline_thickness = 1
    dots_size = 0.1
    dots_spacing = 0.64
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = false
    placeholder_text = Enter Password
    hide_input = false
    rounding = 0
    check_color = rgba(204, 136, 34, 0)
    fail_color = rgba(204, 34, 34, 0)
    fail_text = Authentication Failed
    capslock_color = -1
    position = 0, -180
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] ./scripts/music-progress.sh
    font_size = 16
    font_family = Iosevka
    color = rgba(255, 255, 255, 1.0)
    position = 0, -330
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] ./scripts/music-time.sh
    font_size = 14
    font_family = Iosevka
    color = rgba(255, 255, 255, 1.0)
    position = 0, -290
    halign = center
    valign = center
}

label {
    text = cmd[update:2000] /bin/bash -c 'artist=$(playerctl metadata artist 2>/dev/null); title=$(playerctl metadata title 2>/dev/null); if [[ -n "$artist" && -n "$title" ]]; then echo "${artist} - ${title}"; else echo "Nothing Playing"; fi'
    font_size = 16
    font_family = Iosevka
    color = rgba(255, 255, 255, 1.0)
    position = 0, -420
    halign = center
    valign = center
}

label {
    text = cmd[update:86400000] /bin/bash -c 'date +"%A"'
    color = rgba(255, 255, 255, 1.0)
    font_size = 84
    font_family = Iosevka
    position = 0, 270
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] /bin/bash -c 'date +"%-d %B, %Y"'
    color = rgba(255, 255, 255, 1.0)
    font_size = 20
    font_family = Iosevka
    position = 0, 170
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] /bin/bash -c 'date +"%H:%M"'
    color = rgba(255, 255, 255, 1.0)
    font_size = 16
    font_family = Iosevka
    position = 0, 110
    halign = center
    valign = center
}
